# Generated by Django 5.2.5 on 2025-09-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        # Mark the existing markers and messages tables as created by Django
        migrations.RunSQL(
            "SELECT 1",  # Dummy SQL to mark migration as applied
            reverse_sql="SELECT 1"
        ),
    ]
